name: Build Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'Assets/**'
      - 'Source/**'
  workflow_dispatch: # Allows manual trigger

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: macOS
            os: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        cmake \
        pkg-config \
        libx11-dev \
        libxrandr-dev \
        libxinerama-dev \
        libxcursor-dev \
        libfreetype6-dev \
        libfontconfig1-dev \
        libasound2-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Zip binary (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        powershell Compress-Archive -Path build/SideQick_artefacts/Release/SideQick.exe -DestinationPath build/SideQick_artefacts/Release/SideQick-win64.zip

    - name: Zip binary (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd build/SideQick_artefacts/Release/
        zip -r SideQick-macOS.zip SideQick.app

    - name: Zip binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        zip -j build/SideQick_artefacts/Release/SideQick-linux.zip build/SideQick_artefacts/Release/SideQick

    - name: Upload binary (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: SideQick-win64.zip
        path: build/SideQick_artefacts/Release/SideQick-win64.zip

    - name: Upload binary (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: SideQick-macOS.zip
        path: build/SideQick_artefacts/Release/SideQick-macOS.zip
    
    - name: Upload binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: SideQick-linux.zip
        path: build/SideQick_artefacts/Release/SideQick-linux.zip
